[package]
name = "unwalk"
version = "0.2.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
failure = "=0.1.1"
file = "=1.1.1"
filebuffer = "=0.3.0"
flate2 = "=1.0.1"
serde = "=1.0.37"
serde_derive = "=1.0.37"
structopt = "=0.2.6"
structopt-derive = "=0.2.6"
toml = "=0.4.5"
walkdir = "=2.1.4"

[[bin]]
name = "unwalk"
path = "src/main.rs"
