[package]
name = "ungz-walk"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
clippy = { version = "*", optional = true }
failure = "=0.1.1"
file = "=1.1.1"
filebuffer = "=0.3.0"
flate2 = "=1.0.1"
log = "=0.3.8"
log4rs = "=0.7.0"
simple_logger = "=0.4.0"
structopt = "=0.1.5"
structopt-derive = "=0.1.5"
walkdir = "=2.0.1"

[features]
default = []
