FROM guangie88/rustfmt-clippy:1.26.0-nightly

WORKDIR /app
COPY ./Cargo.toml ./Cargo.lock ./rustfmt.toml ./
COPY ./base/Cargo.toml ./base/rustfmt.toml ./base/
COPY ./gz/Cargo.toml ./gz/rustfmt.toml ./gz/

RUN set -x \
    && cargo fetch --locked -v

COPY ./src/ ./src/
COPY ./base/src/ ./base/src/
COPY ./gz/src/ ./gz/src/

RUN cargo clippy --all \
    && cargo test --all --no-run
