[package]
name = "unwalk-gz"
version = "0.2.0-beta0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
file = "1.1.1"
filebuffer = "0.3.0"
flate2 = "1.0.1"
unwalk-base = { path = "../base" }

[dev-dependencies]
tempfile = "=3.0.0"

[lib]
path = "src/lib.rs"
